service: cfn-nag

provider:
  name: aws
  runtime: java8
  memorySize: 1024
  timeout: 300

package:
  artifact: target/codepipeline-lambda-1.0.0-SNAPSHOT.jar

functions:
  audit:
    handler: JRubyHandlerWrapper
    events:
      - http: POST audit
        path: cfn-nag/audit
